### ISSUE TITLE
[Meta] Dev : Lecture des métriques aggrégées dans udata depuis les logs

### ISSUE THREAD

**Issue by maudetes** [etalab/data.gouv.fr#978]
En terme de fonctionnalité, on ne modifie pas les infos de métriques qu'on a, c'est-à-dire :
- nombre de vues agrégées des datasets
- nombre de téléchargements agrégés des ressources
- nombre de vues agrégées des reuses
- nombre de vues agrégées des organisations

Ces métriques sont maintenant fiabilisées et mise à jour de manière régulière (à priori quotidienne pour commencer).
__

Scénario alternatif : utilisation d'un script maison + base Postgres

- [x] Logs de manière régulière sur Minio
- [x] Script d'aggrégation dans Postgres (à la journée)
- [x] Service API sur Postgres
- [x] #1121
- [x] #1122
